{% set name = "migen" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8fdb776d3556fda82aaa95e936b54196a92afc8427564e94f5ecc34a5681085d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - colorama

test:
  requires:
    - python {{ python_min }}
  imports:
    - migen

about:
  home: https://github.com/m-labs/migen
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python toolbox for building complex digital hardware
  description: A Python toolbox for building complex digital hardware
  dev_url: https://github.com/m-labs/migen

extra:
  recipe-maintainers:
    - timkpaine
